name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: canvassyncer

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: canvassyncer-win.zip
        path: canvassyncer/dist/windows

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        files: canvassyncer-win.zip
