name: Package Application with Pyinstaller

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: canvassyncer/build.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: canvassyncer-win
        path: dist/windows/canvassyncer.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        files: dist/windows/canvassyncer.exe
